### ISSUE TITLE
沙发！

### ISSUE THREAD

**Issue by rcj60560** [arvinljw/SocialHelper#1]
楼主你好 跑了demo qq登录跟分享都没问题，我有个疑问 这个是基于什么sdk来写的 比方说是用的uemngsdk 还是shareSDK？ 在实际项目里引用的话 拓展性强吗 谢谢

**Comment by arvinljw** [comment]
你好，这是根据qq、微信和微博的文档直接集成的。我会根据他们的sdk版本变化，定期更新。

**Comment by rcj60560** [comment]
并不是依赖umeng 或者sharSDK这种三方 而是微博qq微信自己的sdk 版本是最新的吗？ @arvinljw 谢谢

**Comment by arvinljw** [comment]
我上次看的时候是最新版本，对于扩展的话，只需要在SocialHelper里边加入新的参数配置以及三方登录和分享的入口就行，因为这三个都是独立分开的，还是没有什么影响。如果直接使用的话，直接引用就行了。

**Comment by rcj60560** [comment]
感谢！
