### ISSUE TITLE
QQ 登录报错  java.lang.ClassNotFoundException:com.tencent.stat.StatConfig

### ISSUE THREAD

**Issue by 137113715** [arvinljw/SocialHelper#10]
QQ 登录报错
java.lang.ClassNotFoundException: com.tencent.stat.StatConfig
      at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:251)
    at java.lang.Class.forName(Class.java:216)
     at com.tencent.connect.a.a.c(ProGuard:55)
    at com.tencent.connect.auth.c.<init>(ProGuard:42)
      at com.tencent.connect.auth.c.a(ProGuard:77)
     at com.tencent.tauth.Tencent.<init>(ProGuard:59)
      at com.tencent.tauth.Tencent.createInstance(ProGuard:67)
      at net.arvin.socialhelper.QQHelper.<init>(QQHelper.java:44)
     at net.arvin.socialhelper.SocialHelper.loginQQ(SocialHelper.java:40)

**Comment by carozhu** [comment]
请问这个错误是如何解决的

**Comment by arvinljw** [comment]
com.tencent.stat.StatConfig是引用的一个jar包里的，看看是不是jar包没有导进来，open_sdk_r6019_lite.jar

**Comment by taosimple** [comment]
小米8 9.0 也出现这个问题，运行demo调用QQ授权直接崩溃

**Comment by taosimple** [comment]
在9.0以下没问题，或者把 compileSdkVersion targetSdkVersion support都改成 27 在 9.0上也可以运行，但还是没解决问题，只是权宜之计

**Comment by arvinljw** [comment]
可能是Android9.0版本的网络适配问题，报的错是什么？

**Comment by taosimple** [comment]
> 可能是Android9.0版本的网络适配问题，报的错是什么？

好像不是网络问题，就是[第一条](https://github.com/arvinljw/SocialHelper/issues/10#issue-317894107)打印的错误

**Comment by arvinljw** [comment]
那是不是代码混淆的问题？或者是不是jar包导入有问题？你说的是某些版本有问题？

**Comment by taosimple** [comment]
`java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/scheme/SchemeRegistry;
        at com.tencent.open.utils.HttpUtils.getHttpClient(ProGuard:626)
        at com.tencent.open.utils.HttpUtils.openUrl2(ProGuard:506)
        at com.tencent.open.utils.f$1.run(ProGuard:197)`

 真实原因是因为这个，在AndroidManifest.xml文件的application标签里面加入
`<uses-library android:name="org.apache.http.legacy" android:required="false" />` 就好了，腾讯这个真的坑，找了半天

**Comment by arvinljw** [comment]
这个是AndroidP的适配么？所以是编译版本超过28就会有问题？看着对于Apache http api的适配，在6.0以上需要加入如下代码：

```

android {
    useLibrary 'org.apache.http.legacy'
}
```

然后在9.0及其以上，需要添加：

```
<uses-library android:name="org.apache.http.legacy" android:required="false" />
```

才能正常使用。这个好像看着qq的sdk接入没有文档是吧？

**Comment by passself** [comment]
只是加这个不行，还需要更新opensdk

**Comment by saviourdog** [comment]
> 只是加这个不行，还需要更新opensdk

怎么更新啊

**Comment by Klien-m** [comment]
> `java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/scheme/SchemeRegistry; at com.tencent.open.utils.HttpUtils.getHttpClient(ProGuard:626) at com.tencent.open.utils.HttpUtils.openUrl2(ProGuard:506) at com.tencent.open.utils.f$1.run(ProGuard:197)`
> 
> 真实原因是因为这个，在AndroidManifest.xml文件的application标签里面加入
> `<uses-library android:name="org.apache.http.legacy" android:required="false" />` 就好了，腾讯这个真的坑，找了半天

感谢，这个方法解决了我的问题

**Comment by zhaowhao** [comment]
> `java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/scheme/SchemeRegistry; at com.tencent.open.utils.HttpUtils.getHttpClient(ProGuard:626) at com.tencent.open.utils.HttpUtils.openUrl2(ProGuard:506) at com.tencent.open.utils.f$1.run(ProGuard:197)`
> 
> 真实原因是因为这个，在AndroidManifest.xml文件的application标签里面加入 `<uses-library android:name="org.apache.http.legacy" android:required="false" />` 就好了，腾讯这个真的坑，找了半天

Thx

**Comment by Joshua-Chang** [comment]
1.gradle.properties-android.enableJetifier=true
2.implementation("com.android.support:support-v4:23.4.0")
3.gradle-android useLibrary("org.apache.http.legacy")
4.uses-library android:name="org.apache.http.legacy" android:required="false"
