### ISSUE TITLE
微博分享 c8998

### ISSUE THREAD

**Issue by stuartPounds** [arvinljw/SocialHelper#12]
微博分享后 回调显示 success ，却又toast一个分享失败，看了一下微博，刚刚分享的被放入了草稿箱显示了 （c8998）文件不存在。
我看了一下 签名和回调地址都是没问题的

**Comment by arvinljw** [comment]
分享的图片么？我看看你分享的代码是怎么写的呢？

**Comment by xiaozhao0331** [comment]
QQ分享图片好像也调不起来呀  QQ好像现在不支持分享网络图了   我之前写的都是先把图下载下来  然后分享

**Comment by arvinljw** [comment]
都不支持的，都需要保存到本地，分享的图片地址要么是本地文件路径，要么就是app资源内的图片id才行。

**Comment by arvinljw** [comment]
测试了一下，微博分享图片，本地图片是没有问题的。
