### ISSUE TITLE
写的挺不错的  但是还是有点小问题   大佬有空修一下吧  期待下一版

### ISSUE THREAD

**Issue by xiaozhao0331** [arvinljw/SocialHelper#13]
1.微信分享图片，web....调起微信会白屏  看了一下你的源码  好像是  图片的宽高跟大小没有坐限制  
2.QQ分享网络图片  好像是需要先下载下来放到本地  然后用local的方式才能上传成功的   
3. 判断应用是否安装的时候  不存在抛异常会造成app闪退   建议用toast提示一下会更好...
   暂时只看了这么多  微博还没有试    有空的话改一下哟   期待赶紧更新

**Comment by arvinljw** [comment]
好的，谢谢建议，第三的这个不是应用未安装抛的异常，是各种appId为空抛的异常，避免闪退，还是把这部分调整一下。另外两个问题我试一试。

**Comment by arvinljw** [comment]
我抽空检测了一下，发现qq分享图片不需要下载都可以，但是微信和微博是需要本地的。至于第一个问题，微信的掉起白屏应该和图片没有关系，我本地一张比较大的图片都没有影响的。另外第三个已调整，稍后发布新版。
