### ISSUE TITLE
大佬在么 ？请教一个问题

### ISSUE THREAD

**Issue by xiaozhao0331** [arvinljw/SocialHelper#15]
你好  之前请教过你第三方分享这个项目   我这边第三方登录有点问题  什么时候有空能不能帮我看一下  
  我先大致说一下  我们这边也是几个第三方封装在了一起  微博用的是老版的sdk 3.12  但是最近发现微博第三方不能用了   我这边各种调试没有找到原因    web授权页面那个webview页面加载不出来  但是我看断点信息都是正确的  所要加载的那个url也是正确拼接的  但是每次都是progress走到80 然后就无限卡住   然后我新建了一个项目的空包  把分享的框架跟签名单独拿出来  发现在空包里可用  但是在原来的项目中不能用了   看了很久了  很纠结    不知道你有没有遇到过类似的问题   如果方便的话 留个别的联系方式QQ  邮箱 微信都行
    我QQ1016145309

**Comment by arvinljw** [comment]
我的qq，1035407623，我没有遇到过这样的问题，几个第三方封装的一起用是指微信，微博，qq的封装还是别人封装的，你混合使用了？
