### ISSUE TITLE
建议将 accessToken 暴露出来

### ISSUE THREAD

**Issue by yinshudi** [arvinljw/SocialHelper#16]
公司的三方登录都需要 openId 和 accessToken 两个参数。我在 ThirdInfoEntity 中没有找到这个字段，希望可以暴露出来。谢谢。

**Comment by arvinljw** [comment]
目前正在想是否需要把它在库中暴露出来，这里没有返回是安全性的考虑，如果只是存储这个token其实没啥意义，因为这个库每次请求都会重新去获取token。

**解决办法：**
如果是服务端接口要求的话，可以把这个库拉取下来，然后在QQHelper、WBHelper、WXHelper的createThirdInfo方法中，添加上所需的字段即可。第三方的accessToken分别在loginResult，Oauth2AccessToken，wxLoginResult这三个实体里边，其中微博的没有保存为全局变量。

**Comment by yinshudi** [comment]
已经这么解决了，谢谢回复

**Comment by taosimple** [comment]
也建议暴露出来，服务端要用token来对openId验证

**Comment by arvinljw** [comment]
目前新版本已经把AccessToken暴露出来了，可以通过设置是否需要token来配置。
