### ISSUE TITLE
直接使用会有以下错误 unregisterReceiver

### ISSUE THREAD

**Issue by zhangchengzccz** [arvinljw/SocialHelper#17]
hat was originally registered here. Are you missing a call to unregisterReceiver()，虽然在自定义onDestroy方法中调用了unregisterReceiver，但是还是会报错。

**Comment by arvinljw** [comment]
刚更新了readme，需要在onDestroy中调用socialHelper的clear方法，之前没有写上去。demo里也忘了提交。例如下边那样，看看还有问题没有。

```
@Override
protected void onDestroy() {
    super.onDestroy();
    if (socialHelper != null) {
        socialHelper.clear();
    }
}
```

**Comment by zhangchengzccz** [comment]
感谢你的回复，我这边自己修改了。

在 2018-09-13 16:29:07，"arvinljw" <notifications@github.com> 写道：


刚更新了readme，需要在onDestroy中调用socialHelper的clear方法，之前没有写上去。demo里也忘了提交。例如下边那样，看看还有问题没有。

@Override
protected void onDestroy() {
    super.onDestroy();
    if (socialHelper != null) {
        socialHelper.clear();
    }
}
