### ISSUE TITLE
不能调起微博网页授权

### ISSUE THREAD

**Issue by taosimple** [arvinljw/SocialHelper#18]
调起微博APP授权失败，不能调用微博网页授权

**Comment by arvinljw** [comment]
刚验证了一下，是可以吊起微博网页登陆的哦。分享是不能的，因为微博分享是需要客户端的。我再去查看一下是不是现在微博分享不需要查看客户端了。

**Comment by arvinljw** [comment]
验证了一下，官方的demo是可以调起网页的分享的，但是注明了第三方的分享需要客户端支持。详情可以去这里了解一下：[weibo_android_sdk](https://github.com/sinaweibosdk/weibo_android_sdk)

**Comment by taosimple** [comment]
感谢你的回复！

我又测试了一下情况是这样的：

联想zuk手机 ，android8.0 ，安装了微博客户端(去应用市场更新了)
授权不能调起微博客户端，也不能调起网页授权
测试其他APP：
“掘金”不能调起微博客户端，可以调起网页授权
“简书”不能调起微博客户端，可以调起网页授权
“即刻”不能调起微博客户端，也不能调起网页授权

Google nexus5x android8.1
一切正常，可以调起客户端

应该是zuk手机ROM的问题，但是不知道能不能做到像“掘金”那样，调不起客户端的情况下能自动调用网页，这个问题我有空继续查一下看是什么问题

**Comment by arvinljw** [comment]
好的，要是有解决方案，告诉一下，这边也好更新一下。感谢～

**Comment by xiaoying599** [comment]
用这个https://github.com/MobClub/ShareSDK-for-Android可以代码设置微博网页登录还是客户端登录，搞不明白的还可以加QQ4006852216问

**Comment by arvinljw** [comment]
> 用这个https://github.com/MobClub/ShareSDK-for-Android
> 可以代码设置微博网页登录还是客户端登录，搞不明白的还可以加QQ4006852216问

我又重新开了一下官方的demo，网页是可以分享和登录的，但是分享只支持分享文本内容，效果也不好，所以决定目前还是不提供支持微博网页分享的功能，等待后续官方支持之后定会扩展。
至于你说的这个ShareSDK，它内部都还封装了一层的，这违背了我写这个库的初衷，而且它网页分享的时候也只能分享文本。
