### ISSUE TITLE
QQ登陆打通后unionId不对，

### ISSUE THREAD

**Issue by silencefun** [arvinljw/SocialHelper#19]
QQ登陆打通后unionId不对，
诸位有没有遇到。
QQ登陆后 打通后 web/移动端 
取到的 unionId不对，并且是每次不一样。并且不是 应该是UID_XXXX 形式的
使用友盟+ 测试 是返回正确的unionId
当前最新版本的。

**Comment by arvinljw** [comment]
我查了一下文档，发现unionId其实是没有直接在获取token和用户信息时返回的。需要调用一个新的接口，并且申请了unionId，才会返回。我这边尽快加上。
官方参考文档：[unionid介绍](http://wiki.connect.qq.com/unionid介绍)

**Comment by silencefun** [comment]
嗯嗯，好的

**Comment by arvinljw** [comment]
我这边已经加上了，但是没有测试，给你发了邮件到qq邮箱中，不知道可不可以帮我测试一下呢。因为我们公司的这个没有去打通，所以没有申请unionId，测试不到申请之后真实返回的数据。

**Comment by silencefun** [comment]
好的 我测试一下。我也想自己改再看源码 不过你这熟悉改起来快，
//接手别人项目，如果全换 简直是噩梦。

**Comment by arvinljw** [comment]
好的，发给你的那份源码，在请求unionId和userInfo不是同时进行的会慢一些，但是主要是为了测试能不能获取到正确的unionId，可以的话我这边就再优化一下发个新版本，你就可以直接使用了。

**Comment by silencefun** [comment]
好的 在调整测试了

**Comment by silencefun** [comment]
已测试通过。

**Comment by arvinljw** [comment]
v1.2.0版本已添加上该功能。
