### ISSUE TITLE
微信分享，到微信界面后返回，也是回调shareSuccess 方法

### ISSUE THREAD

**Issue by yuan520521** [arvinljw/SocialHelper#20]
如题
微信分享，到微信界面后返回，也是回调shareSuccess 方法

**Comment by arvinljw** [comment]
嗯，这个问题是这样，微信的bug，使用微信提供的demo都是这样。没办法，我给微信发个邮件，希望能及时修改吧，等这个bug没有了我再通知你。

**Comment by arvinljw** [comment]
找到原因了，是微信故意这样做的。他们之前发过申明：[App 分享功能调整](https://open.weixin.qq.com/cgi-bin/announce?spm=a311a.9588098.0.0&action=getannouncement&key=11534138374cE6li&version=)

**Comment by arvinljw** [comment]
暂时没有找到解决办法，这是微信的需求就这样，其他大厂也没办法。微信的目的就是让我们开发者只能取消监听分享回调。
