### ISSUE TITLE
有啥办法去掉微博吗 不引用微博

### ISSUE THREAD

**Issue by Daemon1993** [arvinljw/SocialHelper#21]
我准备jenkins自动化打包 服务器微博的库总是下来不下来 
项目也没需要分享微博 想去掉微博的引用

**Comment by arvinljw** [comment]
其实不使用微博分享是没关系的，配置的时候传空字符串就行；如果是嫌多引用了个微博的包估计就只能clone下代码，把里边的WBHelper相关的去掉就可以了。

**Comment by Daemon1993** [comment]
好的
