### ISSUE TITLE
如果多个activity 都有分享有更优解？

### ISSUE THREAD

**Issue by fengfengfeng1234** [arvinljw/SocialHelper#22]
同标题

**Comment by arvinljw** [comment]
有两种办法，通过封装一个BaseShareActivity里边把通用的分享功能写进去，在用到分享功能的Activity里使用就行了；第二种就是封装一个分享的帮助类，也可以把通用的业务逻辑写进去，在需要的地方引用这个类做相应的操作就可以了。

**Comment by fengfengfeng1234** [comment]
嗯，挺好。
