### ISSUE TITLE
QQ 和微博 Cancel事件没有执行

### ISSUE THREAD

**Issue by pys200603027** [arvinljw/SocialHelper#25]
你好作者，感谢提供这个库

如题，在测试Demo的过程中，发现QQ和微博`cancel`事件没有执行，自己集成到项目中也是一样的

1. QQ/微信/微博可以成功登陆
2. QQ/微博`Cancel`事件没有执行，但是微信`Cancel`事件是可以执行的，弹出Toast“已取消”的提示

**Comment by pys200603027** [comment]
> 你好作者，感谢提供这个库
> 
> 如题，在测试Demo的过程中，发现QQ和微博`cancel`事件没有执行，自己集成到项目中也是一样的
> 
> 1. QQ/微信/微博可以成功登陆
> 2. QQ/微博`Cancel`事件没有执行，但是微信`Cancel`事件是可以执行的，弹出Toast“已取消”的提示

解决方法：`onActivityResult`中取消对data判定null
```
//用处：qq登录和分享回调，以及微博登录回调
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
       //取消data!=null的判定
        if (socialHelper != null) {//qq分享如果选择留在qq，通过home键退出，再进入app则不会有回调
            socialHelper.onActivityResult(requestCode, resultCode, data);
        }
    }
```

**Comment by arvinljw** [comment]
非常感谢，确实是这样，库本身没有问题，就是demo使用的时候把data为空的排除了，所以导致没有监测到取消的情况。稍后我会调整readme和demo中的代码。再次感谢～
