### ISSUE TITLE
微信登录没有触发任何回调

### ISSUE THREAD

**Issue by stuartPounds** [arvinljw/SocialHelper#27]
微信登录正常唤起微信，在微信中点击授权登录没有任何回调。我只希望拿回key_wx_auth_code，不需要其他任何信息，所以我给的WX_APP_SECRET是错误的。

**Comment by arvinljw** [comment]
能问一下这样做的目的是什么吗？如果是有必要的我可以调整一下逻辑，让appSecret的值在需要的时候再判断，如果没有就返回这个code。还有一点，你可以在你的WXEntryActivity中重写public void onResp(BaseResp baseResp)方法，然后在如下代码中获得你要的code：

```
if (baseResp.getType() == ConstantsAPI.COMMAND_SENDAUTH) {
            if (baseResp.errCode == BaseResp.ErrCode.ERR_OK) {
                String code = ((SendAuth.Resp) baseResp).code;
            }
}
```
