### ISSUE TITLE
大佬,微信分享bytes

### ISSUE THREAD

**Issue by zhangqifan1** [arvinljw/SocialHelper#28]
微信分享可不可以加一个图片bytes的- -

**Comment by arvinljw** [comment]
没有问题，下个版本加上，这个版本就先byte保存为图片传进来吧。

**Comment by zhangqifan1** [comment]
保存为图片调用哪个方法- -
这里有俩个方法 但是参数-分别是 String  imageUrl , 和 int  imageResid

**Comment by zhangqifan1** [comment]
额,大佬你的意思是保存到本地,然后传文件地址么

**Comment by arvinljw** [comment]
是的，本地文件，所以是第一个，imgUrl，后一个是图片资源文件用的

**Comment by zhangqifan1** [comment]
好的,谢谢大佬

**Comment by zhangqifan1** [comment]
- -大佬,我获取bitmap 然后 bitmap转字节,然后调用了SocialUtil.bmpToByteArray(bitmap, true);,然后微信分享,--分享出去没有图片--这个是怎么回事啊?

**Comment by arvinljw** [comment]
你是怎么分享的呢？分享不会直接调用SocialUtil.bmpToByteArray(bitmap, true);方法呀，也不支持传bitmap呀

**Comment by zhangqifan1** [comment]
我是Glide.load(bytes).   getFile  ...然后直接传file.getpath

**Comment by arvinljw** [comment]
```
socialHelper.shareWX(this, WXShareEntity.createImageInfo(false, localImgUrl), this);
```

差不多是这样的，localImgUrl就是那个文件的路径。还不清楚的再看看文档嘛，方法上也有注释的。

**Comment by arvinljw** [comment]
通过byte数组分享图片，我试了一下，弊端很大，只能传小图片，在intent的传递中大小也有限制，如果得到的是数组，可以先保存为本地文件再上传。本库本来也可以这样做，但是因为对于文件的使用7.0以上也会有权限的问题，综合考虑之后决定还是不加这个功能。

**Comment by zhangqifan1** [comment]
大佬，我自己拉下来加了一个byte的方法,超过大小 压缩,暂时没问题

**Comment by arvinljw** [comment]
ok

**Comment by zhangqifan1** [comment]
休斯顿、底特律时间?  大佬 咱俩不在一个时区???

**Comment by arvinljw** [comment]
你从哪里看到的？我开了代理的，这个时间也改了？

**Comment by zhangqifan1** [comment]
QQ邮箱的,我懂了,美国节点啊
