### ISSUE TITLE
大佬请教一下如何拿到QQ,微信自带的加载框

### ISSUE THREAD

**Issue by zhangqifan1** [arvinljw/SocialHelper#31]
大佬请教一下如何拿到QQ,微信自带的加载框, - -我找不到....

**Comment by arvinljw** [comment]
什么意思？哪个加载框？

**Comment by zhangqifan1** [comment]
就是 他在调用这个 sdk的时候 会有加载框  ,我现在 要做一个一模一样的  ,可能转圈的不太一样,但是其他的像素要一样,盖上去- -

**Comment by arvinljw** [comment]
这个加载框是进入qq或者微信里边的界面，这个可以让ui设计一个加载框，在调用之前你show出来，在回调完成之后hide就可以了吧？

**Comment by zhangqifan1** [comment]
好滴. 3q
