### ISSUE TITLE
有内存泄漏要怎么没处理呀？

### ISSUE THREAD

**Issue by YeYuDao** [arvinljw/SocialHelper#32]

**Comment by arvinljw** [comment]
```
@Override
protected void onDestroy() {
    super.onDestroy();
    if (socialHelper != null) {
        socialHelper.clear();
    }
}
```

执行了这样的代码了么？

**Comment by YeYuDao** [comment]
执行了，一直报WXApiImpV10.activityCb内存泄漏。还有现在微信分享网页还没有实现网络图片的功能吧

**Comment by arvinljw** [comment]
https://blog.csdn.net/u013134391/article/details/57075210 我搜了一下，不清理可能会存在这样的问题，但是如果执行了clear方法就不会呀，我这边试了一下，都没有存在内存泄漏，你是怎么操作的？我是直接使用微信登陆，得到返回数据。
