### ISSUE TITLE
access_token 

### ISSUE THREAD

**Issue by yang-mr** [arvinljw/SocialHelper#4]
微信登陆的那个  每次都要请求授权吗？   1. 若access_token已超时，那么进行refresh_token会获取一个新的access_token，新的超时时间；
2. 若access_token未超时，那么进行refresh_token不会改变access_token，但超时时间会刷新，相当于续期access_token。大佬  加入他优化呀

**Comment by arvinljw** [comment]
建议不错，其实qq微博都有这个机制，当时图省事就没有加这个功能，下一个版本加。

**Comment by yang-mr** [comment]
建议你把get请求这块 解藕出来 让用户用自己的框架去请求

**Comment by arvinljw** [comment]
我考虑的是如果让用户自己去做，那样做的事就有点多了，用起来就不那么方便。

**Comment by Pinned** [comment]
secret key 放在本地不太安全吧。获取用户信息，还是用服务端来做比较好吧。

**Comment by arvinljw** [comment]
是的放本地是不安全的，但是这些信息appId和secretKey，可以通过接口调用来获取，然后设置就好了，所以该库这样是不影响的。至于accessToken本地我不存也是因为有安全性的考虑在里边。
