### ISSUE TITLE
微信分享后，停留在微信界面，不能触发回调

### ISSUE THREAD

**Issue by clipperL** [arvinljw/SocialHelper#6]
微信分享后，停留在微信界面，不能触发回调
这个问题，楼主有没有解决办法呢？
求助。

**Comment by Pinned** [comment]
微信需要定义WXEntryActivity 吧。

**Comment by arvinljw** [comment]
@clipperL 你好，你说的问题，如果留在微信了，微信也没有提供回调。就好比qq，也是如此，但是qq的情况会更好一点，具体想了解可以细聊。

**Comment by clipperL** [comment]
@arvinljw 在哪聊呢，大佬？要加好友吗？

**Comment by clipperL** [comment]
@Pinned 有WXEntryActivity，分享后返回APP是可以回调的，但是留在微信就不会回调了，永远。

**Comment by arvinljw** [comment]
@clipperL 其实也没啥，就是qq的话，留在qq了，然后返回，再返回退出qq刚好回退到App，这样也是能回调成功，但是留在qq了，选择home键，进入桌面，再进入App，就不能成功回调。

**Comment by clipperL** [comment]
@arvinljw 你说的这种情况，我印象不深了，
“留在qq，选择home键，进入桌面，再进入App，就不能成功回调”，
我记得下边这种情况是可以成功回调的，
"留在qq了，一直返回直到进入App，可以成功回调。"
谢谢。

**Comment by xx394984678** [comment]
虽然微信分享的成功回调我没啥用，但是，微信确实没回调（分享完留在微信的话）。如果有什么新发现，告诉我一下咯
