### ISSUE TITLE
貌似不支持图片网络url的分享呀

### ISSUE THREAD

**Issue by xx394984678** [arvinljw/SocialHelper#7]
如题啦。现在微信最新的分享方式是给它一个bitmap。很想看你是怎么实现网络url的分享的

**Comment by arvinljw** [comment]
对于网络图片，其实可以下载下来，就能得到bitmap了。如果这个需求大的话，之后可以加上这样的辅助功能。

**Comment by pys200603027** [comment]
嗯嗯，是这个问题作者，如果下载下保存到sdcard的话，那还需要权限申请，要是能传递bitmap就好了

**Comment by arvinljw** [comment]
传bitmap的话，如果图片比较大，没有处理过可能会有问题，所以一直在纠结，如果拿到用户传进来的bitmap我再处理一下可能也不好，万一用户就想要传那么大的呢，不好取舍，所以还不如索性就直接传文件，因为这样微信去读取的时候就不会有这个限制了。权限到不是什么大问题，因为一个app，基本的文件读取权限还是都会有的。
