### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by liulinjie1990823** [arvinljw/SocialHelper#9]
除了qqId需要在App的gradle中配置一下，其他的配置都可以放在类库中，让各个平台的的回调实现在自定义的activity中，然后微信的WXEntryActivity重定向到自定义的activity中

**Comment by arvinljw** [comment]
我是这么想的，没有把回调封装到一个自定义Activity中，是因为这样的话就需要强行继承这个Activity会把应用中的继承结构复杂化，自己在使用的时候肯定是可以简单的封装一下再用的。微信那个还可能有微信的其他功能，也会用到这样的Activity所以也没有自定义出去。
